--liquibase formatted sql

--changeset devices11:create-mpa
CREATE TABLE IF NOT EXISTS filmorate.mpa (
                            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar NOT NULL,
                            description varchar,
                            CONSTRAINT mpa_pk PRIMARY KEY (id),
                            CONSTRAINT mpa_unique UNIQUE ("name")
);

comment on table filmorate.mpa is 'Возрастной рейтинг Ассоциации кинокомпаний';
comment on column filmorate.mpa.id is 'Идентификатор рейтинга';
comment on column filmorate.mpa."name" is 'Название рейтинга';
comment on column filmorate.mpa.description is 'Описание';
--rollback DROP TABLE filmorate.mpa;

--changeset devices11:add-mpa-mapping-table
INSERT INTO filmorate.mpa ("name", DESCRIPTION)
VALUES('G', 'Нет возрастных ограничений'),
      ('PG', 'Детям рекомендуется смотреть фильм с родителями'),
      ('PG-13', 'Детям до 13 лет просмотр не желателен'),
      ('R', 'Лицам до 17 лет просматривать фильм можно только в присутствии взрослого'),
      ('NC-17', 'Лицам до 18 лет просмотр запрещён');
--rollback DELETE FROM filmorate.mpa;