--liquibase formatted sql

--changeset devices11:create-film
CREATE TABLE IF NOT EXISTS filmorate.films (
                             film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar,
                             description varchar,
                             release_date date,
                             duration integer,
                             mpa_id integer,
                             CONSTRAINT film_mpa_fk FOREIGN KEY (mpa_id) REFERENCES mpa(id)
);
comment on table filmorate.films is 'Фильмы';
comment on column filmorate.films.film_id is 'Идентификатор фильма';
comment on column filmorate.films."name" is 'Название фильма';
comment on column filmorate.films.description is 'Описание фильма';
comment on column filmorate.films.release_date is 'Дата релиза';
comment on column filmorate.films.duration is 'Продолжительность фильма в минутах';
comment on column filmorate.films.mpa_id is 'Возрастной рейтинг фильма';
--rollback DROP TABLE filmorate.film;

--changeset devices11:create-film_name_idx-index
CREATE INDEX film_name_idx ON filmorate.films ("name",release_date,mpa_id);
--rollback DROP INDEX filmorate.film_name_idx;