--liquibase formatted sql

--changeset devices11:create-genre
CREATE TABLE IF NOT EXISTS filmorate.genres (
                              genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar NOT NULL,
                              CONSTRAINT genre_unique UNIQUE ("name")
);

comment on table filmorate.genres is 'Жанр фильма';
comment on column filmorate.genres.genre_id is 'Идентификатор жанра';
comment on column filmorate.genres."name" is 'Название жанра';
--rollback DROP TABLE public.genre;

--changeset devices11:add-genre-mapping-table
INSERT INTO filmorate.genres (genre_id, "name")
VALUES(1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Мультфильм'),
    (4, 'Триллер'),
    (5, 'Документальный'),
    (6, 'Боевик');
--rollback DELETE FROM filmorate.genre;