--liquibase formatted sql

--changeset YZY4070:create-events
CREATE TABLE IF NOT EXISTS filmorate.events(
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER,
    event_type VARCHAR NOT NULL CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    operation VARCHAR NOT NULL CHECK (operation IN ('REMOVE', 'ADD', 'UPDATE')),
    entity_id INTEGER NOT NULL
);
COMMENT ON TABLE filmorate.events IS 'Таблица событий';
COMMENT ON COLUMN filmorate.events.event_id IS 'ID события';
COMMENT ON COLUMN filmorate.events."timestamp" IS 'Временная отметка';
COMMENT ON COLUMN filmorate.events.user_id IS 'ID пользователя';
COMMENT ON COLUMN filmorate.events.event_type IS 'Тип события';
COMMENT ON COLUMN filmorate.events.operation IS 'Вид операции';
COMMENT ON COLUMN filmorate.events.entity_id IS 'Идентификатор сущности, с которой произошло событие';
--rollback DROP TABLE filmorate.events;